#!/usr/bin/env python3
"""Sync core/ into bindings/native/ for SQLite-style client packaging.

Produces:
  bindings/native/include/     public headers
  bindings/native/src/         private headers + .c sources (mirror)
  bindings/native/sources.txt  relative .c paths (one per line)
  bindings/native/emq_amalgamation.c   unity TU for Go/cgo
  bindings/native/CMakeLists.txt       standalone shared/static build
  bindings/native/VERSION              engine version string
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "core"
NATIVE = ROOT / "bindings" / "native"

# Keep in sync with core/CMakeLists.txt EMQ_SOURCES.
EMQ_SOURCES = [
    "src/platform/emq_platform.c",
    "src/core/emq_alloc.c",
    "src/core/emq_crc.c",
    "src/core/emq_record.c",
    "src/core/emq_log.c",
    "src/core/emq_pool.c",
    "src/core/emq_bitmap.c",
    "src/core/emq_ebr.c",
    "src/core/emq_lfq.c",
    "src/core/emq_cpu.c",
    "src/core/emq_domain.c",
    "src/core/emq_hist.c",
    "src/core/emq_stats_ex.c",
    "src/core/emq_task.c",
    "src/core/emq_compress.c",
    "src/core/emq_fault.c",
    "src/policy/emq_policy.c",
    "src/registry/emq_registry.c",
    "src/sched/emq_wheel.c",
    "src/sched/emq_sched.c",
    "src/routing/emq_routing.c",
    "src/primitives/emq_fifo.c",
    "src/primitives/emq_priority.c",
    "src/primitives/emq_ring.c",
    "src/primitives/emq_delay.c",
    "src/primitives/emq_workqueue.c",
    "src/primitives/emq_stream.c",
    "src/primitives/emq_pubsub.c",
    "src/primitives/emq_dispatch.c",
    "src/engine/emq_mpmc.c",
    "src/engine/emq_engine.c",
    "src/engine/emq_eventloop.c",
    "src/api/emq.c",
]


def read_version() -> str:
    text = (CORE / "CMakeLists.txt").read_text(encoding="utf-8")
    m = re.search(r"project\s*\(\s*EmbeddedMQ\s+VERSION\s+([0-9.]+)", text)
    return m.group(1) if m else "0.0.0"


def copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def write_amalgamation(out_dir: Path) -> None:
    lines = [
        "/* AUTO-GENERATED by scripts/sync_native.py — do not edit. */",
        "#ifndef EMQ_AMALGAMATION",
        "#define EMQ_AMALGAMATION 1",
        "#endif",
        "",
    ]
    for rel in EMQ_SOURCES:
        inner = rel[len("src/") :] if rel.startswith("src/") else rel
        lines.append(f'#include "{inner.replace(chr(92), "/")}"')
    lines.append("")
    (out_dir / "emq_amalgamation.c").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_cmake(out_dir: Path, version: str) -> None:
    src_lines = "\n".join(f"  {s}" for s in EMQ_SOURCES)
    content = f"""# AUTO-GENERATED by scripts/sync_native.py — standalone libemq for bindings.
cmake_minimum_required(VERSION 3.16)
project(emq_native VERSION {version} LANGUAGES C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

option(EMQ_BUILD_SHARED "Build shared libemq" ON)

set(EMQ_SOURCES
{src_lines}
)

function(emq_configure_target tgt)
  target_include_directories(${{tgt}} PUBLIC
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_SOURCE_DIR}}/include>
    PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}}/src)
  if(WIN32)
    target_compile_definitions(${{tgt}} PRIVATE EMQ_PLATFORM_WINDOWS _CRT_SECURE_NO_WARNINGS)
    target_link_libraries(${{tgt}} PUBLIC Synchronization)
  elseif(APPLE)
    target_compile_definitions(${{tgt}} PRIVATE EMQ_PLATFORM_POSIX _DARWIN_C_SOURCE)
    find_package(Threads REQUIRED)
    target_link_libraries(${{tgt}} PUBLIC Threads::Threads)
  else()
    target_compile_definitions(${{tgt}} PRIVATE EMQ_PLATFORM_POSIX _GNU_SOURCE)
    find_package(Threads REQUIRED)
    target_link_libraries(${{tgt}} PUBLIC Threads::Threads)
  endif()
endfunction()

add_library(emq_static STATIC ${{EMQ_SOURCES}})
# On MSVC, a shared target named "emq" also emits emq.lib (import lib).
# Keep the static archive as emq_static.lib in that case to avoid Ninja clashes.
if(MSVC AND EMQ_BUILD_SHARED)
  set_target_properties(emq_static PROPERTIES OUTPUT_NAME emq_static)
else()
  set_target_properties(emq_static PROPERTIES OUTPUT_NAME emq)
endif()
emq_configure_target(emq_static)

if(EMQ_BUILD_SHARED)
  add_library(emq SHARED ${{EMQ_SOURCES}})
  set_target_properties(emq PROPERTIES
    OUTPUT_NAME emq
    VERSION {version}
    SOVERSION 0
    WINDOWS_EXPORT_ALL_SYMBOLS ON)
  if(NOT MSVC)
    set_target_properties(emq PROPERTIES C_VISIBILITY_PRESET hidden)
  endif()
  target_compile_definitions(emq PUBLIC EMQ_BUILD_SHARED=1 PRIVATE EMQ_EXPORTS=1)
  emq_configure_target(emq)
endif()

install(TARGETS emq_static ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
if(EMQ_BUILD_SHARED)
  install(TARGETS emq ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
endif()
install(DIRECTORY include/ DESTINATION include)
"""
    (out_dir / "CMakeLists.txt").write_text(content, encoding="utf-8")


def populate(out_dir: Path, version: str) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    copy_tree(CORE / "include", out_dir / "include")
    copy_tree(CORE / "src", out_dir / "src")
    (out_dir / "sources.txt").write_text("\n".join(EMQ_SOURCES) + "\n", encoding="utf-8")
    (out_dir / "VERSION").write_text(version + "\n", encoding="utf-8")
    (out_dir / "README.md").write_text(
        "# Bundled EmbeddedMQ native sources\n\n"
        "Generated by `python scripts/sync_native.py` from `core/`.\n"
        "Used by language bindings so users never need a separate cmake build.\n",
        encoding="utf-8",
    )
    write_amalgamation(out_dir)
    write_cmake(out_dir, version)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if native/ is out of date")
    args = parser.parse_args()

    version = read_version()
    for rel in EMQ_SOURCES:
        if not (CORE / rel).is_file():
            print(f"missing source: {rel}", file=sys.stderr)
            return 1

    staging = NATIVE.with_name("native.staging")
    populate(staging, version)

    if args.check and NATIVE.exists():
        for name in ("sources.txt", "VERSION", "emq_amalgamation.c", "CMakeLists.txt"):
            if (staging / name).read_bytes() != (NATIVE / name).read_bytes():
                print(f"out of date: {name}", file=sys.stderr)
                shutil.rmtree(staging)
                return 2
        shutil.rmtree(staging)
        print("bindings/native is up to date")
        return 0

    if NATIVE.exists():
        shutil.rmtree(NATIVE)
    staging.rename(NATIVE)

    # Vendor into language package trees (pip / crates.io require in-tree sources).
    for dest in (
        ROOT / "bindings" / "python" / "native",
        ROOT / "bindings" / "rust" / "emq-sys" / "native",
    ):
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(NATIVE, dest)

    # Go cgo only compiles .c files in the package directory (not subdirs).
    # Emit one wrapper per TU: zz_<path>.c -> #include "../native/src/..."
    go_dir = ROOT / "bindings" / "go"
    for old in go_dir.glob("zz_*.c"):
        old.unlink()
    for rel in EMQ_SOURCES:
        flat = "zz_" + rel[len("src/") :].replace("/", "_")
        wrapper = (
            "/* AUTO-GENERATED by scripts/sync_native.py — do not edit. */\n"
            "#if !defined(EMQ_SYSTEM_LIB)\n"
            f'#include "../native/{rel}"\n'
            "#endif\n"
        )
        (go_dir / flat).write_text(wrapper, encoding="utf-8")

    print(f"synced bindings/native (engine {version}, {len(EMQ_SOURCES)} sources)")
    print("vendored -> bindings/python/native, bindings/rust/emq-sys/native")
    print(f"go wrappers  -> bindings/go/zz_*.c ({len(EMQ_SOURCES)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
